// react_client/src/components/AuthForm.jsx
import React, { useEffect, useState, forwardRef } from 'react';

const AuthForm = forwardRef(({
    title,
    buttonTitle,
    isRegistering,
    submitForm,
    formData,
    setFormData,
    loading,
    isUpdating,
}, ref) => {
    useEffect(() => {
        !formData && setFormData(prev => prev = {
            ...formData
        });
    }, [formData])

    const [touched, setTouched] = useState({})

    const handleTouch = (e) => {
        const { name } = e.target;
        setTouched(prev => prev = {
            ...touched,
            [name]: true,
        });
    }

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => prev = {
            ...formData,
            [name]: value,
        });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        submitForm(formData);
    };

    const isValidform = () => {
        if (isUpdating) {
            return (
                formData.name !== ''
                && formData.surname !== ''
                && /^3\d{9}$/.test(formData.phone)
            )
        } else if (isRegistering) {
            return (
                formData.name !== ''
                && formData.surname !== ''
                && /^3\d{9}$/.test(formData.phone)
                && /^[\w.%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email)
                && /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{8,}/.test(formData.password)
            )
        } else {
            return (
                /^[\w.%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email)
            )
        }
    }

    return (
        <form className="card" onSubmit={handleSubmit}>
            <div className="card-content">
                <span className="card-title">{title}</span>
                {isRegistering && (
                    <>
                        <div className="input-field">
                            <input
                                type="text"
                                id="name"
                                autoComplete="off"
                                onChange={handleChange}
                                value={formData.name}
                                onBlur={handleTouch}
                                name="name"
                                required
                                className={(formData.name === '' && touched.name ? 'error-input error-text' : '')}
                            />
                            <label htmlFor="name" className={(formData.name === '' && touched.name ? 'error-text' : '')}>{isUpdating ? 'Actualizar Nombre:' : 'Nombre:'}</label>
                            {
                                (
                                    formData.name === '' && touched.name
                                ) ? (<span className="helper-text red-text">
                                    <span>El nombre es requerido</span>
                                </span>)
                                : <></>
                            }
                        </div>
                        <div className="input-field">
                            <input
                                type="text"
                                id="surname"
                                autoComplete="off"
                                onChange={handleChange}
                                value={formData.surname}
                                onBlur={handleTouch}
                                name="surname"
                                required
                                className={(formData.surname === '' && touched.surname ? 'error-input error-text' : '')}
                            />
                            <label htmlFor="surname" className={(formData.surname === '' && touched.surname ? 'error-text' : '')}>{isUpdating ? 'Actualizar Apellido:' : 'Apellido:'}</label>
                            {
                                (
                                    formData.surname === '' && touched.surname
                                ) ? (<span className="helper-text red-text">
                                    <span>El apellido es requerido</span>
                                </span>)
                                : <></>
                            }
                        </div>
                        <div className="input-field">
                            <input
                                type="tel"
                                id="phone"
                                autoComplete="off"
                                onChange={handleChange}
                                value={formData.phone}
                                onBlur={handleTouch}
                                name="phone"
                                maxLength="10"
                                required
                                className={(!/^3\d{9}$/.test(formData.phone) && touched.phone ? 'error-input error-text' : '')}
                            />
                            <label htmlFor="phone" className={(!/^3\d{9}$/.test(formData.phone) && touched.phone ? 'error-text' : '')}>{isUpdating ? 'Actualizar Teléfono:' : 'Teléfono:'}</label>
                            {
                                (
                                    !/^3\d{9}$/.test(formData.phone) && touched.phone
                                ) ? (<span className="helper-text red-text">
                                    {
                                        (
                                            formData.phone === ''
                                        ) ? (<span>El teléfono es requerido</span>)
                                        : (<span>El formato del teléfono es incorrecto</span>)
                                    }
                                </span>)
                                : <></>
                            }
                        </div>
                    </>
                )}
                {
                    isUpdating
                    ?? <><div className="input-field">
                        <input
                            type="email"
                            id="email"
                            autoComplete="off"
                            onChange={handleChange}
                            value={formData.email}
                                onBlur={handleTouch}
                            name="email"
                            required
                                className={(!/^[\w.%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email) && touched.email ? 'error-input error-text' : '')}
                        />
                        <label htmlFor="email" className={(!/^[\w.%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email) && touched.email ? 'error-text' : '')}>Email:</label>
                            {
                                (
                                    !/^[\w.%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email) && touched.email
                                ) ? (<span className="helper-text red-text">
                                    {
                                        (
                                            formData.email === ''
                                        ) ? (<span>El email es requerido</span>)
                                        : (<span>El formato del email es incorrecto</span>)
                                    }
                                </span>)
                                : <></>
                            }
                    </div>
                        <div className="input-field">
                            <input
                                type="password"
                                id="password"
                                autoComplete="off"
                                onChange={handleChange}
                                value={formData.password}
                                onBlur={handleTouch}
                                name="password"
                                required
                                className={(!/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{8,}/.test(formData.password) && touched.password ? 'error-input error-text' : '')}
                            />
                            <label htmlFor="password" className={(!/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{8,}/.test(formData.password) && touched.password ? 'error-text' : '')}>Contraseña:</label>
                            {
                                (
                                    !/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{8,}/.test(formData.password) && touched.password
                                ) ? (<span className="helper-text red-text">
                                    {
                                        (
                                            formData.password === ''
                                        ) ? (<span>La contraseña es requerido</span>)
                                        : (<span>El formato de la contraseña es incorrecto</span>)
                                    }
                                </span>)
                                : <></>
                            }
                        </div></>
                }
            </div>
            <div className="card-action">
                <button className="modal-action btn waves-effect" type="submit" disabled={!isValidform() || loading}>
                    {buttonTitle}
                </button>
            </div>
        </form>
    );
});

export default AuthForm;

// angular_client/src/app/shared/components/auth-form/component/auth-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import {
      FormBuilder,
      FormControl,
      FormGroup,
      Validators,
} from "@angular/forms";
import { UserInterface } from "../../../interfaces/auth.interface";

@Component({
      selector: "crm-auth-form",
      templateUrl: "./auth-form.component.html",
      styleUrls: ["./auth-form.component.css"],
})
export class AuthFormComponent implements OnInit {
      @Input("title") titleProps!: string;
      @Input("buttonTitle") buttonTitleProps!: string;
      @Output() emitAuthForm = new EventEmitter<UserInterface>();
      @Input() isRegistering: boolean = false;
      @Input() isUpdating: boolean = false;
      authForm!: FormGroup;

      requiredPasswordLength = 3;

      emailIsValid(): boolean {
            return (
                  this.authForm.controls["email"].errors &&
                  this.authForm.controls["email"].errors["email"]
            );
      }

      constructor(private fb: FormBuilder) { }
      submitForm() {
            this.authForm.disable();
            this.emitAuthForm.emit(this.authForm.value);
      }

      ngOnInit(): void {
            const formControls: any = { };

            if (this.isUpdating) {
                  formControls['name'] = new FormControl(null, Validators.required);
                  formControls['surname'] = new FormControl(null, Validators.required);
                  formControls['phone'] = new FormControl(null, [Validators.required, Validators.minLength(10), Validators.maxLength(10)]);
            } else if (this.isRegistering) {
                  formControls['email'] = new FormControl(null, [
                        Validators.required,
                        Validators.email,
                  ]);
                  formControls['password'] = new FormControl(null, [
                        Validators.required,
                        Validators.minLength(this.requiredPasswordLength),
                  ]);
                  formControls['name'] = new FormControl(null, Validators.required);
                  formControls['surname'] = new FormControl(null, Validators.required);
                  formControls['phone'] = new FormControl(null, [Validators.required, Validators.minLength(10), Validators.maxLength(10)]);
            } else {
                  formControls['email'] = new FormControl(null, [
                        Validators.required,
                        Validators.email,
                  ]);
                  formControls['password'] = new FormControl(null, [
                        Validators.required,
                        Validators.minLength(this.requiredPasswordLength),
                  ]);
            }

            this.authForm = this.fb.group(formControls);
      }

}

<form class="card" [formGroup]="authForm" (ngSubmit)="submitForm()">
      <div class="card-content">
            <span class="card-title">{{ titleProps }}</span>
            <div class="input-field" *ngIf="isRegistering">
                  <input id="name" type="text" [formControlName]="'name'" [ngClass]="{
                              invalid:
                                    authForm.get('name')?.invalid &&
                                    authForm.get('name')?.touched
                        }" />
                  <label for="name">{{isUpdating ? 'Actualizar Nombre:' : 'Nombre:'}}</label>
                  <span class="helper-text red-text" *ngIf="
                              authForm.get('name')?.invalid &&
                              authForm.get('name')?.touched
                        "><span *ngIf="
                                    (authForm.get('name')?.errors)!['required']
                              ">El nombre es requerido</span></span>
            </div>
            <div class="input-field" *ngIf="isRegistering">
                  <input id="surname" type="text" [formControlName]="'surname'" [ngClass]="{
                              invalid:
                                    authForm.get('surname')?.invalid &&
                                    authForm.get('surname')?.touched
                        }" />
                  <label for="surname">{{isUpdating ? 'Actualizar Apellido:' : 'Apellido:'}}</label>
                  <span class="helper-text red-text" *ngIf="
                              authForm.get('surname')?.invalid &&
                              authForm.get('surname')?.touched
                        "><span *ngIf="
                                    (authForm.get('surname')?.errors)!['required']
                              ">El apellido es requerido</span></span>
            </div>
            <div class="input-field" *ngIf="isRegistering">
                  <input id="phone" type="tel" [formControlName]="'phone'" maxlength="10" [ngClass]="{
                              invalid:
                                    authForm.get('phone')?.invalid &&
                                    authForm.get('phone')?.touched
                        }" />
                  <label for="phone">{{isUpdating ? 'Actualizar Teléfono:' : 'Teléfono:'}}</label>
                  <span class="helper-text red-text" *ngIf="
                              authForm.get('phone')?.invalid &&
                              authForm.get('phone')?.touched
                        "><span *ngIf="
                                    (authForm.get('phone')?.errors)!['required']
                              ">Teléfono es requerido</span>
                              <span *ngIf="
                              (authForm.get('phone')?.errors)![
                                    'minlength'
                              ] &&
                              (authForm.get('phone')?.errors)![
                                    'minlength'
                              ]['requiredLength']
                        ">Requiere un mínimo de 10 caracteres</span></span>
            </div>
            <div class="input-field" *ngIf="!isUpdating">
                  <input id="email" type="email" [formControlName]="'email'" [ngClass]="{
                              invalid:
                                    authForm.get('email')?.invalid &&
                                    authForm.get('email')?.touched
                        }" />
                  <label for="email">Email:</label>
                  <span class="helper-text red-text" *ngIf="
                              authForm.get('email')?.invalid &&
                              authForm.get('email')?.touched
                        "><span *ngIf="
                                    (authForm.get('email')?.errors)!['required']
                              ">El email es requerido</span><span
                              *ngIf="(authForm.get('email')?.errors)!['email']">Formato de email
                              incorrecto</span></span>
            </div>
            <div class="input-field" *ngIf="!isUpdating">
                  <input id="password" type="password" [formControlName]="'password'" [ngClass]="{
                              invalid:
                                    authForm.get('password')?.invalid &&
                                    authForm.get('password')?.touched
                        }" />
                  <label for="password">Contraseña:</label>
                  <span class="helper-text red-text" *ngIf="
                              authForm.get('password')?.invalid &&
                              authForm.get('password')?.touched
                        ">
                        <span *ngIf="
                                    (authForm.get('password')?.errors)![
                                          'minlength'
                                    ] &&
                                    (authForm.get('password')?.errors)![
                                          'minlength'
                                    ]['requiredLength']
                              ">Requiere un mínimo de {{ requiredPasswordLength }} caracteres, pero actualmente son
                              {{
                              (authForm.get("password")?.errors)![
                              "minlength"
                              ]["actualLength"]
                              }}</span><span *ngIf="
                                    (authForm.get('password')?.errors)![
                                          'required'
                                    ]
                              ">La contraseña es requerida</span>
                  </span>
            </div>
      </div>
      <div class="card-action">
            <button class="modal-action btn waves-effect" type="submit"
                  [disabled]="!authForm.valid || authForm.disabled">{{ buttonTitleProps }}</button>
      </div>
</form>
