// react_client/src/components/MailingSchemasComponent/MailingSchemaForm.jsx
import React, { useEffect, useState, useRef } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import ConfirmDialog from './ConfirmDialog';
import { RouterPathsEnum } from '../../api/enums/routerPaths.enum.tsx';
import EmailSchemasService from '../../api/services/EmailSchemasService.jsx';
import moment from 'moment';

function MailingSchemaForm() {
    const { id } = useParams();
    const isNew = id === 'new';
    const emailSchemaFormRef = useRef(null);
    const [emailSchema, setEmailSchema] = useState({
        _id: null,
        name: '',
        subject: '',
        sendDate: '',
        templateUrl: '',
    });
    const [emailSchemaCharged, setEmailSchemaCharged] = useState('');
    const [isFileSelected, setIsFileSelected] = useState(false);
    const [loading, setLoading] = useState(false);
    const routerPathsEnum = RouterPathsEnum;
    const fileInputRef = useRef(null);

    const navigate = useNavigate();

    useEffect(() => {
        if (!isNew) {
            return EmailSchemasService.getEmailSchemaById(id)
                .then(response => {
                    setEmailSchema(prev => prev = {
                        ...response,
                        sendDate: moment(response.sendDate).format('YYYY-MM-DD')
                    })
                    setEmailSchemaCharged(prev => prev = response.templateUrl);
                    return setIsFileSelected(true);
                }).catch(errors => console.error(errors))
        }
    }, [isNew, id]);

    const handleChange = ev => {
        if (['name', 'subject', 'sendDate'].includes(ev.target.id)) {
            setEmailSchema({
                ...emailSchema,
                [ev.target.id]:
                    ev.target.id === 'sendDate'
                        ? moment(ev.target.value).format('YYYY-MM-DD')
                        : ev.target.value
            })
        }
    }

    const isInvalidForm = ev => {
        return (
            emailSchema.name === ''
            || emailSchema.sendDate === ''
            || emailSchema.subject === ''
            || emailSchemaCharged === ''
        ) 
    }

    const removeEmailSchema = () => {
        const decision = window.confirm(`¿Estás seguro de que deseas eliminar el esquema de correo electrónico ${emailSchema.name}?`);

        if (decision && id) {
            EmailSchemasService.deleteEmailSchema(id)
                .then(() => {
                    navigate("/" + routerPathsEnum.MAILING)
                })
                .catch((error) => {
                    console.error('Error deleting email schema:', error);
                });
        }
    };

    const submitForm = async (event) => {
        event.preventDefault();
        setLoading(true);

        const sendForm = {
            name: emailSchema.name,
            sendDate: emailSchema.sendDate,
            subject: emailSchema.subject,
            templateUrl: emailSchemaCharged,
        };

        try {
            if (isNew) {
                EmailSchemasService.createEmailSchema(sendForm).then(response => {
                    navigate("/" + routerPathsEnum.MAILING + "/" + response._id);
                })
            } else {
                await EmailSchemasService.updateEmailSchema(id, sendForm);
                navigate("/" + routerPathsEnum.MAILING + "/" + id);
            }
            setEmailSchema((prev) => ({ ...prev, ...sendForm }));
        } catch (error) {
            console.error('Error:', error);
        } finally {
            setLoading(false);
        }
    };


    const downloadFileInput = () => {
        if (isFileSelected && typeof emailSchemaCharged === 'string') {
            const content = emailSchemaCharged;
            const a = document.createElement('a');
            a.style.display = 'none';
            a.href = content;
            a.download = 'email-schema.html';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        }
    };

    const onFileUpload = (event) => {
        const file = event.target.files[0];

        if (file) {
            const reader = new FileReader();

            reader.onload = (e) => {
                if (e.target && typeof e.target.result === 'string') {
                    setEmailSchemaCharged(e.target.result);
                    setIsFileSelected(true);
                }
            };

            reader.readAsDataURL(file);
        }
    };

    const showFileInput = () => {
        if (fileInputRef.current) {
            fileInputRef.current.click();
        }
    };

    return (
        <main className="content">
            <div className="page-title">
                <h4>
                    <Link to={`/${routerPathsEnum.MAILING}`}>Esquemas</Link>
                    <i className="material-icons">keyboard_arrow_right</i>
                    {isNew ? 'Agregar' : 'Actualizar'} Esquema
                </h4>
                <span>
                    <button className="btn btn-small red" disabled={isNew} onClick={removeEmailSchema}>
                        <i className="material-icons">delete</i>
                    </button>
                </span>
            </div>

            <div className="row">
                <form ref={emailSchemaFormRef} onChange={handleChange} className="col s12 l6">
                    <div className="input-field">
                        <input id="name" type="text" value={emailSchema.name} />
                        <label htmlFor="name">Nombre</label>
                    </div>

                    <div className="input-field">
                        <input id="subject" type="text" value={emailSchema.subject} />
                        <label htmlFor="subject">Asunto</label>
                    </div>

                    <div className="input-field">
                        <input id="sendDate" type="date" value={emailSchema.sendDate} />
                        <label htmlFor="sendDate">Fecha en que se enviará</label>
                    </div>

                    <div>
                        <input type="file" style={{ display: 'none' }} ref={fileInputRef} onChange={onFileUpload} />
                        <button type="button" className="waves-effect waves-light btn orange lighten-2 mb2" onClick={showFileInput}>
                            <i className="material-icons left">backup</i>
                            Cargar esquema HTML
                        </button>
                        <button type="button" disabled={!isFileSelected} className="waves-effect waves-light btn blue lighten-2 mb2" onClick={downloadFileInput}>
                            <i className="material-icons left">download</i>
                            Descargar esquema HTML
                        </button>
                    </div>
                    <div>
                        <button onClick={submitForm} className="waves-effect waves-light btn" disabled={isInvalidForm() || loading}>
                            Guardar cambios
                        </button>
                    </div>
                </form>
            </div>
        </main>
    );
}

export default MailingSchemaForm;

// angular_client/src/app/modules/mailing/components/mailing-schema-form/mailing-schema-form.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from "@angular/core";
import { RouterPathsEnum } from "../../../../shared/enums/routerPaths.enum";
import { Subject, firstValueFrom, fromEvent, of, switchMap, takeUntil } from "rxjs";
import { ActivatedRoute, Router } from "@angular/router";
import { FormBuilder, FormControl, FormGroup, Validators } from "@angular/forms";
import { MaterialService } from "../../../../shared/classes/material.service";
import { MatDialog } from "@angular/material/dialog";
import { ConfirmMailDialogComponent } from "./confirm-dialog/confirm-dialog.component";
import { EmailSchemaInterface } from "src/app/shared/interfaces/email-schema.interface";
import { MatDatepicker } from "@angular/material/datepicker";
import { EmailSchemasService } from "src/app/shared/services/email/email.service";
import * as moment from "moment";

@Component({
      selector: "crm-mailing-schema-form",
      templateUrl: "./mailing-schema-form.html",
      styleUrls: ["./mailing-schema-form.css"],
})
export class MailingSchemaFormComponent implements OnInit, OnDestroy {
      emailSchema?: EmailSchemaInterface;
      emailSchemaId?: string;
      isNew = true;
      emailSchemaForm: FormGroup;
      private isAlive = new Subject<void>();
      image: File | undefined;
      emailSchemaCharged: string | File | ArrayBuffer | null = "";
      emailHtmlFile: string | File | undefined | null = "";
      isFileSelected = false;
      routerPathsEnum = RouterPathsEnum;
      @ViewChild("fileInput") fileInput!: ElementRef<HTMLInputElement>;
      @ViewChild("delButton", { static: true }) delButton!: ElementRef<HTMLButtonElement>;

      private destroy$ = new Subject<void>();

      constructor(
            private dialog: MatDialog,
            private fb: FormBuilder,
            private route: ActivatedRoute,
            private router: Router,
            private emailSchemasService: EmailSchemasService,
            private materialService: MaterialService,
      ) {
            this.emailSchemaForm = new FormGroup({
                  name: new FormControl(null, [Validators.required, Validators.minLength(2)]),
                  subject: new FormControl(null, [Validators.required, Validators.minLength(2)]),
                  sendDate: new FormControl(null, [Validators.required]),
                  templateUrl: new FormControl(null, [Validators.required]),

            });
      }

      ngOnInit(): void {
            this.initializeRouterParams();
            this.initializeDeleteStream();
      }

      ngOnDestroy(): void {
            this.destroy$.next();
            this.destroy$.complete();
      }

      private initializeDeleteStream() {
            fromEvent(this.delButton.nativeElement, "click")
                  .pipe(takeUntil(this.isAlive))
                  .subscribe(() => this.removeEmailSchema());
      }

      private initializeRouterParams() {
            this.route.params
                  .pipe(
                        switchMap((params: { id?: string }) => {
                              if (params.id) {
                                    this.isNew = false;
                                    this.emailSchemaId = params.id;
                                    return this.emailSchemasService.getEmailSchemaById(params.id);
                              }
                              return of(null);
                        }),
                        takeUntil(this.destroy$)
                  )
                  .subscribe(
                        (emailSchema: EmailSchemaInterface | null) => {
                              if (emailSchema) {
                                    this.emailSchema = emailSchema;
                                    this.emailSchemaCharged = emailSchema.templateUrl;
                                    this.isFileSelected = true;
                                    this.emailSchemaForm.patchValue({
                                          name: emailSchema.name,
                                          subject: emailSchema.subject,
                                          sendDate: moment(emailSchema.sendDate).format('YYYY-MM-DD'),
                                          templateUrl: emailSchema.templateUrl,
                                    });
                              }
                        },
                        (error: any) => this.materialService.toast(error.error.message)
                  );
      }

      async submitForm() {
            if (this.emailSchemaForm.invalid) {
                  this.materialService.toast("El formulario no es válido. Por favor, revise los errores.");
                  return;
            }

            this.emailSchemaForm.disable();

            const formValue = this.emailSchemaForm.value;

            try {
                  if (this.isNew) {
                        const newEmailSchema = await firstValueFrom(this.emailSchemasService.createEmailSchema(formValue));
                        this.router.navigate(["/emails/", newEmailSchema._id]);
                        this.materialService.toast("El esquema ha sido creado.");
                  } else if (this.emailSchemaId) {
                        await firstValueFrom(this.emailSchemasService.updateEmailSchema(this.emailSchemaId, formValue));
                        this.router.navigate(["/emails",this.emailSchemaId]);
                        this.materialService.toast("El esquema ha sido actualizado.");
                  }

            } catch (error) {
                  this.materialService.toast("Error al guardar el esquema.");
            } finally {
                  if (this.emailSchemaForm.disabled) {
                        this.emailSchemaForm.enable();
                  }
            }
      }

      removeEmailSchema() {
            const decision = window.confirm(
                  `¿Estás seguro de que deseas eliminar el esquema de correo electrónico ${this.emailSchema?.name}?`
            );

            if (decision && this.emailSchemaId) {
                  this.emailSchemasService.deleteEmailSchema(this.emailSchemaId).subscribe(
                        () => {
                        this.router.navigate(["/emails"]);
                        },
                        (error) => { }
                  );
            }
      }

      openConfirmMailDialog(): void {
            const dialogRef = this.dialog.open(ConfirmMailDialogComponent, {
                  width: "250px",
            });

            dialogRef.afterClosed().subscribe((result) => { });
      }

      showFileInput() {
            this.fileInput.nativeElement.click();
      }

      downloadFileInput(): void {
            if (this.isFileSelected && typeof this.emailSchemaCharged === 'string') {
                  const content = this.emailSchemaCharged;
                  const a = document.createElement('a');
                  a.style.display = 'none';
                  a.href = content;
                  a.download = 'email-schema.html';
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
            }
      }



      onFileUpload(event: Event) {
            const element = event.target as HTMLInputElement;
            const file = element.files![0];

            if (file) {
                  const reader = new FileReader();

                  reader.onload = (e) => {
                        if (e.target && typeof e.target.result === "string") {
                              this.emailSchemaForm.get("templateUrl")?.setValue(e.target.result);
                              this.emailSchemaCharged = e.target.result;
                              this.isFileSelected = true;
                        }
                  };

                  reader.readAsDataURL(file);
            }
      }
}
