// angular_client/src/app/modules/history/components/history.component.ts
import {
      AfterViewInit,
      Component,
      ElementRef,
      OnDestroy,
      OnInit,
      ViewChild,
} from "@angular/core";
import {
      MaterialInterface,
      MaterialService,
} from "../../../shared/classes/material.service";
import { OrdersService as HttpOrdersService, OrdersService } from "../../../shared/services/orders/orders.service";
import { Subject, takeUntil } from "rxjs";
import { environment } from "../../../../enviroments/environment";
import { FilterInterface } from "../../../shared/interfaces/filter.interface";
import { OrderInterface } from "src/app/shared/interfaces/option.interface";
import { AuthService } from "../../../shared/services/auth/auth.service";

@Component({
      selector: "crm-history",
      templateUrl: "./history.component.html",
      styleUrls: ["./history.component.css"],
})
export class HistoryComponent implements AfterViewInit, OnDestroy, OnInit {
      showFilter = false;
      offset = 0;
      limit = environment.STEP;
      filterTooltip!: MaterialInterface;
      historyList: OrderInterface[] = [];
      isAlive = new Subject<void>();
      @ViewChild("tooltip") tooltipRef: ElementRef | undefined;
      loadingFlag = false;
      reloadingFlag = false;
      noMoreFlag = false;
      private filter: FilterInterface = {};
      constructor(
            private materialService: MaterialService,
            private ordersService: OrdersService,
            private authService: AuthService,
      ) { }
      triggerFilter() {
            this.showFilter = !this.showFilter;
            this.changeTooltipNotification();
            if (!this.showFilter && !!Object.keys(this.filter).length) {
                  this.historyList = [];
                  this.filter = {};
                  this.fetch();
            }
      }

      reloadContent() {
            this.historyList = [];
            this.offset = 0;
            this.filter = {};
            this.reloadingFlag = true;
            this.fetch();
      }

      onOrderFinished() {
            this.reloadContent();
      }

      loadMore() {
            this.loadingFlag = true;
            this.offset += environment.STEP;
            this.fetch();
      }

      ngAfterViewInit(): void {
            this.filterTooltip = this.materialService.initTooltip(
                  this.tooltipRef?.nativeElement,
            );
      }

      ngOnDestroy(): void {
            this.isAlive.next();
            this.isAlive.complete();
            this.filterTooltip.destroy();
      }

      private changeTooltipNotification() {
            if (this.showFilter) {
                  this.tooltipRef?.nativeElement.setAttribute(
                        "data-tooltip",
                        "Close tooltip",
                  );
            } else {
                  this.tooltipRef?.nativeElement.setAttribute(
                        "data-tooltip",
                        "Open tooltip",
                  );
            }
      }

      ngOnInit(): void {
            this.reloadingFlag = true;
            this.fetch();
      }

      private fetch() {
            const params: { offset: number; limit: number } = {
                  offset: this.offset,
                  limit: this.limit,
            };

            if (this.authService.isAdmin()) {
                  this.ordersService.getAllOrders(params)
                        .pipe(takeUntil(this.isAlive))
                        .subscribe(
                              (orders: OrderInterface[]) => {
                                    this.historyList = [...this.historyList, ...orders];
                                    this.loadingFlag = false;
                                    this.reloadingFlag = false;
                                    this.noMoreFlag = orders.length < this.limit;
                              },
                              (error: Error) => {
                                    console.error('Error fetching orders:', error);
                              }
                        );
            } else {
                  const currentUserId = this.authService.getCurrentUserId();
                  if (currentUserId) {
                        this.ordersService.getOrdersByUser(currentUserId, params)
                              .pipe(takeUntil(this.isAlive))
                              .subscribe(
                                    (orders: OrderInterface[]) => {
                                          this.historyList = [...this.historyList, ...orders];
                                          this.loadingFlag = false;
                                          this.reloadingFlag = false;
                                          this.noMoreFlag = orders.length < this.limit;
                                    },
                                    (error: Error) => { 
                                          console.error('Error fetching orders:', error);
                                    }
                              );
                  } else {
                        console.error('Error fetching orders: Current user ID is undefined.');
                  }
            }
      }


      applyFilter($event: FilterInterface) {
            this.historyList = [];
            this.offset = 0;
            this.filter = $event;
            this.reloadingFlag = true;
            this.fetch();
      }

      isFiltered(): boolean {
            return !!Object.keys(this.filter).length;
      }
}

<main class="content">
      <div class="page-title">
            <h4>Historial de Pedidos</h4>
            <button #tooltip (click)="triggerFilter()" class="btn btn-small"
                  [ngClass]="{ opened: showFilter, red: isFiltered() }" [disabled]="!historyList" data-option="left"
                  data-tooltip="Filtrar...">
                  <i class="material-icons">filter_list</i>
            </button>
            <button (click)="reloadContent()" class="btn btn-small" [disabled]="reloadingFlag" data-tooltip="Recargar">
                  <i class="material-icons">refresh</i>
            </button>
      </div>


      <div class="card">
            <div class="card-content">
                  <ng-container *ngIf="showFilter">
                        <crm-history-list (orderFinished)="onOrderFinished()"
                              [historyList]="historyList"></crm-history-list>
                  </ng-container>
                  <ng-container *ngIf="!reloadingFlag; else reloading">
                        <ng-container *ngIf="historyList.length; else empty">
                              <crm-history-list [historyList]="historyList"></crm-history-list>
                        </ng-container>
                        <ng-template #empty>
                              <div class="center">No hay pedidos</div>
                        </ng-template>
                        <div class="center mb2" *ngIf="!noMoreFlag">
                              <button [disabled]="noMoreFlag" *ngIf="!loadingFlag; else loading"
                                    class="btn waves-effect grey darken-1 btn-small" (click)="loadMore()">Cargar
                                    más</button>
                              <ng-template #loading>
                                    <crm-loader></crm-loader>
                              </ng-template>
                        </div>
                  </ng-container>
            </div>
      </div>
      <ng-template #reloading>
            <crm-loader></crm-loader>
      </ng-template>
</main>

// react_client/src/components/HistoryComponent/History.jsx
import React, { useEffect, useRef, useState } from 'react';
import HistoryFilter from './HistoryFilter';
import HistoryList from './HistoryList';
import { environment } from '../../enviroments/environment';
import { Subject } from 'rxjs';
import OrderService from '../../api/services/OrderService';
import AuthService from '../../api/services/AuthService';
import LoaderComponent from '../LoaderComponent';
import './styles.css'

function HistoryComponent() {
    const [showFilter, setShowFilter] = useState(false);
    const [offset, setOffset] = useState(0);
    const [limit] = useState(environment.STEP);
    const [historyList, setHistoryList] = useState([]);
    const [loadingFlag, setLoadingFlag] = useState(false);
    const [reloadingFlag, setReloadingFlag] = useState(false);
    const [noMoreFlag, setNoMoreFlag] = useState(false);
    const [filter, setFilter] = useState({});
    const [isAlive] = useState(new Subject());
    const tooltipRef = useRef(null);

    const [isModalOpen, setIsModalOpen] = useState(false);
    const [selectedOrder, setSelectedOrder] = useState(null);

    const currentUser = AuthService.getCurrentUser();

    useEffect(() => {
        fetchHistory();
        return () => isAlive.next();
    }, [offset, limit]);

    const changeTooltipNotification = () => {
        if (tooltipRef.current) {
            if (showFilter) {
                tooltipRef.current.setAttribute('data-tooltip', 'Close tooltip');
            } else {
                tooltipRef.current.setAttribute('data-tooltip', 'Open tooltip');
            }
        }
    };

    const triggerFilter = () => {
        setShowFilter(!showFilter);
        changeTooltipNotification();
        if (!showFilter && Object.keys(filter).length > 0) {
            setHistoryList([]);
            setFilter({});
            fetchHistory();
        }
    };

    const reloadContent = () => {
        setHistoryList([]);
        setOffset(0);
        setFilter({});
        setReloadingFlag(true);
        fetchHistory();
    };

    const onOrderFinished = () => {
        reloadContent();
    };

    const loadMore = () => {
        setOffset((prev) => prev + environment.STEP);
        fetchHistory();
    };

    const fetchHistory = () => {
        setLoadingFlag(true);
        const params = { offset, limit };
        if (currentUser.admin) {
            OrderService.getAllOrders({ ...params })
                .then((response) => {
                    setNoMoreFlag(response.length < limit);
                    setLoadingFlag(false);
                    setHistoryList([...historyList, ...response]);
                })
                .catch((error) => {
                    console.error('Error fetching orders:', error);
                });
        } else {
            OrderService.getOrdersByUser({ userId: currentUser._id, ...params })
                .then((response) => {
                    setNoMoreFlag(response.length < limit);
                    setLoadingFlag(false);
                    setHistoryList([...historyList, ...response]);
                })
                .catch((error) => {
                    console.error('Error fetching orders:', error);
                });
        }
    };

    const applyFilter = (event) => {
        setHistoryList([]);
        setOffset(0);
        setFilter(event);
        setReloadingFlag(true);
        fetchHistory();
    };

    const isFiltered = () => {
        return Object.keys(filter).length > 0;
    };

    const openModal = () => {
        setIsModalOpen(true);
    };

    const closeModal = () => {
        setIsModalOpen(false);
    };

    return (
        <>
            <main className="content">
                <div className="page-title">
                    <h4>Historial de Pedidos</h4>
                    <button
                        onClick={triggerFilter}
                        className={`btn btn-small${showFilter ? ' opened' : ''}${isFiltered() ? 'red' : ''}`}
                        disabled={!historyList}
                        data-option="left"
                        data-tooltip={showFilter ? 'Close tooltip' : 'Open tooltip'}
                    >
                        <i className="material-icons">filter_list</i>
                    </button>
                    <button
                        onClick={reloadContent}
                        className="btn btn-small"
                        disabled={reloadingFlag}
                        data-tooltip="Recargar"
                    >
                        <i className="material-icons">refresh</i>
                    </button>
                </div>
                {showFilter && <HistoryFilter onFilter={applyFilter} />}
                <div className="card">
                    <div className="card-content">
                        {loadingFlag ? (
                            <LoaderComponent />
                        ) : (
                            <>
                                {historyList.length ? (
                                    <HistoryList
                                        historyList={historyList}
                                        orderFinished={onOrderFinished}
                                        openModal={openModal}
                                        closeModal={closeModal}
                                        isModalOpen={isModalOpen}
                                        setSelectedOrder={setSelectedOrder}
                                    />
                                ) : (
                                    <div className="center">No hay pedidos</div>
                                )}
                                <div className="center mb2" style={{ display: noMoreFlag ? 'none' : 'block' }}>
                                    <button
                                        disabled={noMoreFlag}
                                        onClick={loadMore}
                                        className="btn waves-effect grey darken-1 btn-small"
                                    >
                                        Cargar más
                                    </button>
                                </div>
                            </>
                        )}
                    </div>
                </div>
            </main>
        </>
    );
}

export default HistoryComponent;
